boards/urls.py
from django.urls import path

from .views import (
    BoardDetailView,
    BoardListView,
    JobCreateView,
    JobUpdateView,
    JobDeleteView,
    BoardCreateView,
    BoardUpdateView,
    BoardDeleteView,
    scrape_job,
)

urlpatterns = [
    path("", BoardListView.as_view(), name="board_list"),
    path("new/", BoardCreateView.as_view(), name="board_create"),
    path("<str:board_slug>/", BoardDetailView.as_view(), name="board_detail"),
    path("<str:board_slug>/edit/", BoardUpdateView.as_view(), name="board_update"),
    path("<str:board_slug>/delete/", BoardDeleteView.as_view(), name="board_delete"),
    path("<str:board_slug>/jobs/new/", JobCreateView.as_view(), name="job_create"),
    path("<str:board_slug>/jobs/new/scrape/", scrape_job, name="scrape_job"),
    path("<str:board_slug>/jobs/<str:job_slug>/edit/", JobUpdateView.as_view(), name="job_update"),
    path("<str:board_slug>/jobs/<str:job_slug>/delete/", JobDeleteView.as_view(), name="job_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from pages.views import custom_handler404, custom_handler500

handler404 = custom_handler404
handler500 = custom_handler500

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("pages.urls")),
    path("boards/", include("boards.urls")),
    path("tasks/", include("tasks.urls")),
    path("metrics/", include("metrics.urls")),
]

pages/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
]

boards/models.py
import shortuuid

from django.db import models
from django.urls import reverse
from django.utils.timezone import now
from django.utils.safestring import mark_safe
from django.contrib.auth import get_user_model


class TimeStampMixin(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Board(TimeStampMixin):
    icon = models.CharField(max_length=2, default="💼")
    title = models.CharField(max_length=100)
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    slug = models.SlugField(
        default="",
        max_length=8,
    )

    def save(self, *args, **kwargs):
        # only generate slug on first save
        if not self.pk:
            rand_slug = str(shortuuid.uuid())[:8]
            self.slug = rand_slug
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse("board_detail", kwargs={"board_slug": self.slug})


class Job(TimeStampMixin):
    company = models.CharField(max_length=100, help_text=mark_safe("Logos provided by <a href='https://clearbit.com' target='_blank'>Clearbit</a>."))
    logo = models.CharField(default="https://via.placeholder.com/130?text=Company+Logo", max_length=100)
    title = models.CharField(max_length=100)
    deadline = models.DateField(default=now, blank=True)
    PROGRESS_CHOICES = (
        ("applied", "Applied"),
        ("phone", "Phone"),
        ("onsite", "Onsite"),
        ("offer", "Offer"),
    )
    progress = models.CharField(max_length=8, choices=PROGRESS_CHOICES)
    description = models.TextField(blank=True, null=True)
    board = models.ForeignKey(
        Board,
        related_name="jobs",
        on_delete=models.CASCADE,
    )
    slug = models.SlugField(
        default="",
        max_length=8,
    )

    class Meta:
        ordering = ["deadline"]

    def save(self, *args, **kwargs):
        if not self.pk:
            rand_slug = str(shortuuid.uuid())[:8]
            self.slug = rand_slug
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.title} at {self.company}"

    def get_absolute_url(self):
        return reverse("board_detail", kwargs={"board_slug": self.board.slug})

tasks/models.py
from django.db import models

from boards.models import Job


class Task(models.Model):
    task = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False)
    job = models.ForeignKey(
        Job,
        related_name="tasks",
        on_delete=models.CASCADE,
    )

    class Meta:
        ordering = [
            "date",
        ]

    def __str__(self):
        return self.task

boards/forms.py
import emoji

from django.utils.safestring import mark_safe
from django.forms import ModelForm, ValidationError
from django.forms.widgets import TextInput
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Layout, Row, Column, Submit, HTML
from crispy_forms.bootstrap import AppendedText

from .models import Board, Job

from summernote.widgets import SummernoteInplaceWidget


class BoardForm(ModelForm):
    def clean_icon(self):
        icon = self.cleaned_data["icon"]
        if icon not in emoji.UNICODE_EMOJI["en"]:
            raise ValidationError("Icon needs to be an emoji.")
        return icon

    class Meta:
        model = Board
        fields = ("icon", "title")
        labels = {"icon": ""}
        widgets = {"icon": TextInput(attrs={"type": "button", "class": "bg-transparent fs-3 grey-hover"})}


class JobForm(ModelForm):
    class Meta:
        model = Job
        fields = ("company", "logo", "title", "deadline", "progress", "description")
        labels = {"company": ""}
        widgets = {"description": SummernoteInplaceWidget()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Field("logo", type="hidden"),
            HTML(
                "<div class='position-relative d-inline-block'><img src='{% if job %}{{ job.logo }}{% else %}https://via.placeholder.com/130?text=Company+Logo{% endif %}' id='logo' class='img-fluid border rounded-2 mb-3'><span id='clear_logo' class='position-absolute top-0 end-0 cursor-pointer'><i class='bi bi-x fs-4'></i></span></div>"
            ),
            AppendedText(
                "company",
                mark_safe("<div class='dropdown'><button id='company_dropdown_button' class='btn' type='button' data-bs-toggle='dropdown'><i class='bi bi-search'></i></button><ul class='dropdown-menu dropdown-menu-end' id='company_dropdown_menu'></ul></div>"),
                placeholder="Enter a company name",
                autocomplete="off",
            ),
            Row(
                Column("title"),
                Column("progress"),
            ),
            "deadline",
            "description",
            Submit("submit", "Save", css_class="btn-dark"),
        )

boards/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import JsonResponse, HttpResponse
from django.urls import reverse

from .models import Board, Job
from .forms import BoardForm, JobForm
from .serializers import BoardSerializer, JobSerializer
from .scrape import get_job_info

from tasks.forms import TaskForm
from utils.mixins import ajax_required, BoardPermissionMixin, JobPermissionMixin, FormInvalidStatus400Mixin


@ajax_required
@login_required
def scrape_job(request, board_slug):
    if request.method == "GET":
        url = request.GET.get("jobUrl")
        data = get_job_info(url)
        return JsonResponse(data)


class BoardListView(LoginRequiredMixin, ListView):
    model = Board
    template_name = "boards/board_list.html"
    context_object_name = "boards"

    def get_queryset(self):
        objs = self.model.objects
        return objs.filter(user=self.request.user)


class BoardCreateView(LoginRequiredMixin, FormInvalidStatus400Mixin, CreateView):
    model = Board
    form_class = BoardForm
    template_name = "boards/board_create.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        return super().form_valid(form)


class BoardDetailView(LoginRequiredMixin, BoardPermissionMixin, DetailView):
    model = Board
    slug_url_kwarg = "board_slug"
    template_name = "boards/board_detail.html"
    redirect_url = "board_list"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["columns"] = ("applied", "phone", "onsite", "offer")
        job_serializer = JobSerializer(self.object.jobs, many=True)
        context["jobs"] = job_serializer.data
        return context


class BoardUpdateView(LoginRequiredMixin, BoardPermissionMixin, FormInvalidStatus400Mixin, UpdateView):
    model = Board
    slug_url_kwarg = "board_slug"
    form_class = BoardForm
    template_name = "boards/board_update.html"

    def form_valid(self, form):
        self.object = form.save()
        board_serializer = BoardSerializer(instance=self.object)
        return JsonResponse({"board": board_serializer.data})


class BoardDeleteView(LoginRequiredMixin, BoardPermissionMixin, DeleteView):
    model = Board
    slug_url_kwarg = "board_slug"
    form_class = BoardForm
    template_name = "boards/board_delete.html"

    def get_success_url(self):
        return reverse("board_list")


class JobCreateView(LoginRequiredMixin, BoardPermissionMixin, FormInvalidStatus400Mixin, CreateView):
    model = Job
    form_class = JobForm
    template_name = "boards/job_create.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["board"] = self.get_board()
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.board = self.get_board()
        self.object = form.save()
        job_serializer = JobSerializer(instance=self.object)
        return JsonResponse({"job": job_serializer.data})


class JobUpdateView(LoginRequiredMixin, JobPermissionMixin, FormInvalidStatus400Mixin, UpdateView):
    model = Job
    slug_url_kwarg = "job_slug"
    form_class = JobForm
    template_name = "boards/job_update.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tasks"] = self.object.tasks.all()
        context["task_form"] = TaskForm()
        return context
    
    def form_valid(self, form):
        self.object = form.save()
        job_serializer = JobSerializer(instance=self.object)
        return JsonResponse({"job": job_serializer.data})


class JobDeleteView(LoginRequiredMixin, JobPermissionMixin, DeleteView):
    model = Job
    slug_url_kwarg = "job_slug"
    template_name = "boards/job_delete.html"

    def form_valid(self, form):
        self.object.delete()
        return HttpResponse(status=204)

templates/boards/board_create.html
{% load crispy_forms_tags %}

<form action="{% url 'board_create' %}" onsubmit="handleBoardCreateFormSubmit(event)">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">New Board</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        {{ form|crispy }}
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-dark me-auto">Create</button>
    </div>
</form>

<script type="module">
    import { EmojiButton } from "https://cdn.jsdelivr.net/npm/@joeattardi/emoji-button@latest/dist/index.min.js";

    const picker = new EmojiButton({
        position: "bottom-start",
        showPreview: false,
        autoFocusSearch: false,
        emojisPerRow: 6,
        rows: 4
    });
    
    const iconInput = document.querySelector("#id_icon");

    picker.on("emoji", selection => {
        iconInput.value = selection.emoji;
    });

    iconInput.addEventListener("click", (e) => {
        e.preventDefault();
        e.stopPropagation();
        picker.togglePicker(iconInput)
    });
</script>
<script>
    async function handleBoardCreateFormSubmit(e) {
        e.preventDefault();
        const iconField = {"icon": document.querySelector("#id_icon").value};
        const form = e.target;
        const response = await submitForm(form, [iconField]);
        if (response.redirected) {
            window.location.href = response.url;
        } else {
            const template = await response.text();
            const modalContent = form.closest(".modal-content");
            setInnerHTML(modalContent, template);
        }
    };
</script>

templates/boards/board_delete.html
<form action="{% url 'board_delete' board.slug %}" onsubmit="handleBoardDeleteFormSubmit(event)">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">Delete Board</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        <p class="lead">Are you sure you want to delete this board?</p>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-danger me-auto">Delete</button>
    </div>
</form>

<script>
    async function handleBoardDeleteFormSubmit(e) {
        e.preventDefault();
        const form = e.target;
        const response = await submitForm(form);
        if (response.ok) {
            window.location.href = response.url;
        }
    };
</script>

templates/boards/board_detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link href="{% static 'css/app.css' %}" rel="stylesheet">
{% endblock style %}

{% block content %}
{% include 'app/header.html' %}
{% include 'app/sidebar.html' %}
{{ jobs|json_script:"jobs" }}
<main>
    <div class="container-fluid cpx-0 pt-3">
        <div class="row g-0 align-items-center mb-3">
            <div class="col-8 text-truncate">
                <h3 id="boardTitle">{{ board.icon }} {{ board }}</h3>
            </div>
            <div class="col-4 pb-1 text-end">
                <a href="{% url 'board_update' board.slug %}" data-modal="#smallModal" onclick="showModal(event)">
                    <i class="bi bi-pencil fs-5"></i>
                </a>
                <a href="{% url 'board_delete' board.slug %}" data-modal="#smallModal" onclick="showModal(event)">
                    <i class="bi bi-trash fs-5 ms-2"></i>
                </a>
            </div>
        </div>
        <div class="row flex-row flex-nowrap overflow-y-hidden">
            {% for column in columns %}
            <div class="col-12 col-sm-6 col-lg-4 col-xl-3">
                <div class="kanban-column d-flex flex-column position-relative rounded-top">
                    <div class="px-3 py-2">
                        <h5 class="fw-bold">{{ column|title }}</h5>
                    </div>
                    <div class="px-2 py-0 dyn-height overflow-x-hidden" id="{{ column }}" style="flex: 1 1 auto;">
                    </div>
                </div>
                <a href="{% url 'job_create' board.slug %}" class="add-card-btn w-100 border-0 rounded-bottom" data-modal="#largeModal" onclick="showModal(event)">
                    <i class="bi bi-plus"></i>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock content %}

{% block modal %}
<div class="modal fade" id="smallModal">
    <div class="modal-dialog">
        <div class="modal-content"></div>
    </div>
</div>
<div class="modal fade" id="largeModal">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content"></div>
    </div>
</div>
{% endblock modal %}

{% block script %}
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/clearbitSearchBar.js' %}"></script>
<script>  
    document.addEventListener("DOMContentLoaded", (e) => {
        document.addEventListener("hidden.bs.modal", (e) => {
            e.target.querySelector(".modal-content").innerHTML = "";
        });
    });

    const state = {
        jobs: JSON.parse(document.querySelector("#jobs").textContent),
    };

    renderJobs();
</script>
{% endblock script %}

templates/boards/board_list.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}

{% block style %}
<link href="{% static 'css/app.css' %}" rel="stylesheet">
{% endblock style %}

{% block content %}
{% include 'app/header.html' %}
{% include 'app/sidebar.html' %}
<main>
    <div class="container-fluid cpx-0 pt-3">
        <div class="content">
            <div class="row g-0 align-items-center mb-3">
                <div class="col-8">
                    <h3>Boards</h3>
                </div>
                <div class="col-4 pb-1 text-end">
                    <a href="{% url 'board_create' %}" data-modal="#smallModal" onclick="showModal(event)">
                        <i class="bi bi-plus-lg fs-5"></i>
                    </a>
                </div>
            </div>
            <div class="row g-4">
                {% for board in boards %}
                <div class="col-12 col-sm-6 col-md-4">
                    <div class="border rounded p-3 bg-white grey-hover btm-shadow" role="button" id="boardCard"
                        data-url="{{ board.get_absolute_url }}">
                        <h3>{{ board.icon }}</h3>
                        <h5 class="fw-bold text-truncate">{{ board }}</h5>
                        <span>{{ board.updated_at|timesince|upto:"," }} ago</span>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
{% endblock content %}

{% block modal %}
<div class="modal fade" id="smallModal">
    <div class="modal-dialog">
        <div class="modal-content"></div>
    </div>
</div>
{% endblock modal %}

{% block script %}
<script src="{% static 'js/main.js' %}"></script>
<script>
    document.addEventListener("DOMContentLoaded", (e) => {
        document.addEventListener("hidden.bs.modal", (e) => {
            e.target.querySelector(".modal-content").innerHTML = "";
        });

        document.querySelectorAll("#boardCard").forEach((card) => {
            card.addEventListener("click", (e) => {
                window.location = e.currentTarget.dataset.url;
            });
        });
    });
</script>
{% endblock script %}

templates/boards/board_update.html
{% load crispy_forms_tags %}

<form action="{% url 'board_update' board.slug %}" onsubmit="handleBoardUpdateFormSubmit(event)">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">Edit Board</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        {{ form|crispy }}
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-dark me-auto">Edit</button>
    </div>
</form>

<script type="module">
    import { EmojiButton } from "https://cdn.jsdelivr.net/npm/@joeattardi/emoji-button@latest/dist/index.min.js";

    const picker = new EmojiButton({
        position: "bottom-start",
        showPreview: false,
        autoFocusSearch: false,
        emojisPerRow: 6,
        rows: 4
    });
    
    const iconInput = document.querySelector("#id_icon");

    picker.on("emoji", selection => {
        iconInput.value = selection.emoji;
    });

    iconInput.addEventListener("click", (e) => {
        e.preventDefault();
        e.stopPropagation();
        picker.togglePicker(iconInput)
    });
</script>
<script>
    async function handleBoardUpdateFormSubmit(e) {
        e.preventDefault();
        const iconField = {"icon": document.querySelector("#id_icon").value};
        const form = e.target;
        const response = await submitForm(form, [iconField]);
        if (!response.ok) {
            const template = await response.text();
            const modalContent = form.closest(".modal-content");
            setInnerHTML(modalContent, template);
        } else {
            const data = await response.json();
            document.querySelector("#boardTitle").innerText = `${data.board.icon} ${data.board.title}`;
            const modalEl = form.closest(".modal");
            const modal = bootstrap.Modal.getOrCreateInstance(modalEl);
            modal.hide();
        }
    };
</script>

templates/boards/job_create.html
{% load crispy_forms_tags %}

<div class="modal-header">
    <h3>Add Job</h3>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
    <div class="mb-3">
        <label for="jobUrl">URL</label>
        <div class="input-group">
            <input type="url" class="form-control"
                placeholder="https://www.example.co.uk/viewjob?jk=8e32db7a&q=grad&l=glasgow" id="jobUrl">
            <a href="{% url 'scrape_job' board.slug %}" class="btn btn-outline-dark" onclick="scrapeJob(event)">Scrape</a>
        </div>
        <small class="form-text text-muted">Web scraping is currently only supported for job postings on Indeed,
            Totaljobs and Reed.</small>
    </div>
    <form action="{% url 'job_create' board.slug %}" class="pb-3" onsubmit="handleJobCreateFormSubmit(event)">
        {% crispy form %}
    </form>
</div>

<script>
    async function scrapeJob(e) {
        e.preventDefault();
        const url = new URL(e.currentTarget.href);
        const jobUrl = document.getElementById("jobUrl").value;
        url.searchParams.append("jobUrl", jobUrl);
        const requestOptions = {
            method: "GET",
            headers: { "X-Requested-With": "XMLHttpRequest" },
        };
        const response = await fetch(url, requestOptions);
        const data = await response.json();
        if (response.ok) {
            document.querySelector("#id_company").value = data.company;
            document.querySelector("#id_title").value = data.title;
            $(document.querySelector("#id_description")).summernote("code", data.description);
        }
    };

    async function handleJobCreateFormSubmit(e) {
        e.preventDefault();
        const form = e.target;
        const response = await submitForm(form);
        if (!response.ok) {
            const template = await response.text();
            const modalContent = form.closest(".modal-content");
            setInnerHTML(modalContent, template);
        } else {
            const data = await response.json();
            const nextJobs = [...state.jobs, data.job];
            nextJobs.sort((a, b) => Date.parse(a.deadline) - Date.parse(b.deadline));
            state.jobs = nextJobs;
            renderJobs();
            const modalEl = form.closest(".modal");
            const modal = bootstrap.Modal.getOrCreateInstance(modalEl);
            modal.hide();
        }
    };

    document.querySelector("#clear_logo").addEventListener("click", (e) => {
        document.querySelector("#logo").src = "https://via.placeholder.com/130?text=Company+Logo";
        document.querySelector("#id_logo").value = "https://via.placeholder.com/130?text=Company+Logo";
    });

    initClearbitSearchBar("id_company", "company_dropdown_button", "company_dropdown_menu");
</script>

templates/boards/job_delete.html
<form action="{% url 'job_delete' job.board.slug job.slug %}" data-job="{{ job.slug }}"
    onsubmit="handleJobDeleteFormSubmit(event)">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">Delete Job</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        <p class="lead">Are you sure you want to delete this job?</p>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-danger me-auto">Delete</button>
    </div>
</form>

<script>
    async function handleJobDeleteFormSubmit(e) {
        e.preventDefault();
        const form = e.target;
        const jobSlug = form.dataset.job;
        const response = await submitForm(form);
        if (response.ok) {
            const nextJobs = state.jobs.filter((job) => job.slug !== jobSlug);
            state.jobs = nextJobs;
            renderJobs();
            const modalEl = form.closest(".modal");
            const modal = bootstrap.Modal.getOrCreateInstance(modalEl);
            modal.hide();
        }
    };
</script>

templates/boards/job_update.html
{% load crispy_forms_tags %}

<div class="modal-header d-block pb-0">
    <div class="d-flex align-items-center mb-3">
        <h3 class="mb-0">Job: {{ job.slug }}</h3>
        <button type="button" class="btn-close mt-0" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <nav class="nav nav-justified mb-0" id="tabs">
        <a href="#" class="nav-item nav-link text-dark active" data-tab="info">
            <i class="bi bi-info-square align-middle fs-5"></i>
            Info
        </a>
        <a href="#" class="nav-item nav-link text-dark" data-tab="tasks">
            <i class="bi bi-sticky align-middle fs-5"></i>
            Tasks
        </a>
    </nav>
</div>
<div class="modal-body">
    <div class="tabcontent" id="info">
        <form action="{% url 'job_update' job.board.slug job.slug %}" class="pb-3" data-job="{{ job.slug }}"
            onsubmit="handleJobUpdateFormSubmit(event)">
            {% csrf_token %}
            {% crispy form %}
        </form>
    </div>
    <div class="tabcontent" id="tasks" hidden>
        <div id="taskCreateForm">
            {% include "tasks/task_create.html" with form=task_form %}
        </div>
        <div class="pb-3" id="taskList">
            {% include 'tasks/task_list.html' %}
        </div>
    </div>
</div>

<script>
    document.querySelectorAll(".nav-link").forEach((navLink) => {
        navLink.addEventListener("click", (e) => {
            e.preventDefault();
            e.stopPropagation();
            const clickedTab = e.currentTarget.dataset.tab;
            document.querySelector("#tabs .active").classList.remove("active");
            document.querySelectorAll(".tabcontent").forEach((el) => {
                el.toggleAttribute("hidden");
            });
            e.currentTarget.classList.add("active");
        });
    });

    async function handleJobUpdateFormSubmit(e) {
        e.preventDefault();
        const form = e.target;
        const jobSlug = form.dataset.job;
        const response = await submitForm(form);
        if (!response.ok) {
            const template = await response.text();
            const modalContent = form.closest(".modal-content");
            setInnerHTML(modalContent, template);
        } else {
            const data = await response.json();
            const nextJobs = state.jobs.map((job) => job.slug === jobSlug ? { ...data.job } : job);
            nextJobs.sort((a, b) => Date.parse(a.deadline) - Date.parse(b.deadline));
            state.jobs = nextJobs;
            renderJobs();
            const modalEl = form.closest(".modal");
            const modal = bootstrap.Modal.getOrCreateInstance(modalEl);
            modal.hide();
        }
    };

    document.querySelector("#clear_logo").addEventListener("click", (e) => {
        document.querySelector("#logo").src = "https://via.placeholder.com/130?text=Company+Logo";
        document.querySelector("#id_logo").value = "https://via.placeholder.com/130?text=Company+Logo";
    });

    initClearbitSearchBar("id_company", "company_dropdown_button", "company_dropdown_menu");
</script>