config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from pages.views import custom_handler404, custom_handler500

handler404 = custom_handler404
handler500 = custom_handler500

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("pages.urls")),
    path("boards/", include("boards.urls")),
    path("tasks/", include("tasks.urls")),
    path("metrics/", include("metrics.urls")),
]

pages/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
]

tasks/urls.py
from django.urls import path

from .views import TaskCreateView
from .api import TaskDetailView

urlpatterns = [
    path("", TaskCreateView.as_view(), name="task_create"),
    path("<int:pk>/", TaskDetailView.as_view(), name="task_detail"),
]

tasks/models.py
from django.db import models

from boards.models import Job


class Task(models.Model):
    task = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False)
    job = models.ForeignKey(
        Job,
        related_name="tasks",
        on_delete=models.CASCADE,
    )

    class Meta:
        ordering = [
            "date",
        ]

    def __str__(self):
        return self.task

tasks/forms.py
from django.forms import ModelForm
from crispy_forms.layout import Layout
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from crispy_forms.bootstrap import FieldWithButtons

from .models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ("task",)
        labels = {"task": ""}
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            FieldWithButtons("task", Submit("submit", "Add", css_class="btn-dark"))
        )

tasks/views.py
from django.template.response import TemplateResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views.generic.edit import CreateView

from .models import Task
from .forms import TaskForm

from boards.models import Job
from utils.mixins import JobPermissionMixin, FormInvalidStatus400Mixin


class TaskCreateView(LoginRequiredMixin, JobPermissionMixin, FormInvalidStatus400Mixin, CreateView):
    http_method_names = ["post"]
    model = Task
    form_class = TaskForm
    template_name = "tasks/task_create.html"

    # need to override this JobPermissionMixin method since url wont include job slug param
    def get_job(self):
        job_slug = self.request.POST.get("job-slug")
        return get_object_or_404(Job, slug=job_slug)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["job"] = self.get_job()
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.job = self.get_job()
        self.object = form.save()
        return TemplateResponse(self.request, "tasks/task.html", {"task": self.object})

templates/tasks/task.html
<div class="d-flex justify-content-between align-items-center border bg-white rounded p-3 mb-1" id="taskCard" data-id="{{ task.id }}">
    <input type="checkbox" onchange="completeTask(event)" {% if task.completed %}checked{% endif %}>
    <label class="text-truncate px-2 me-auto">
        {{ task }}
    </label>
    <a href="#" onclick="deleteTask(event)">
        <i class="bi bi-x-square-fill"></i>
    </a>
</div>

templates/tasks/task_create.html
{% load crispy_forms_tags %}

<form action="{% url 'task_create' %}" onsubmit="handleTaskCreateFormSubmit(event)">
    <input type="hidden" name="job-slug" value="{{ job.slug }}">
    {% crispy form %}
</form>

<script>
    async function handleTaskCreateFormSubmit(e) {
        e.preventDefault();
        const form = e.target;
        const response = await submitForm(form);
        if (!response.ok) {
            const template = await response.text();
            document.querySelector("#taskCreateForm").innerHTML = template;
        } else {
            const template = await response.text();
            const input = form.querySelector("#id_task");
            if (input.classList.contains("is-invalid")) {
                input.classList.remove("is-invalid");
                form.querySelector("[id^='error_']").remove();
            }
            form.reset();
            document.querySelector("#taskList").innerHTML += template;
        }
    };
</script>

templates/tasks/task_list.html
{% for task in tasks %}
    {% include "tasks/task.html" %}
{% endfor %}

<script>
    async function completeTask(e) {
        const taskCard = e.target.closest("#taskCard");
        const taskId = taskCard.dataset.id;
        const url = `/tasks/${taskId}/`;
        const csrfToken = document.querySelector("input[name=csrfmiddlewaretoken]").value;
        const requestOptions = {
            method: "PATCH",
            headers: { "X-CSRFToken": csrfToken },
        };
        const response = await fetch(url, requestOptions);
    };

    async function deleteTask(e) {
        const taskCard = e.target.closest("#taskCard");
        const taskId = taskCard.dataset.id;
        const url = `/tasks/${taskId}/`;
        const csrfToken = document.querySelector("input[name=csrfmiddlewaretoken]").value;
        const requestOptions = {
            method: "DELETE",
            headers: { "X-CSRFToken": csrfToken },
        };
        const response = await fetch(url, requestOptions);
        if (response.ok) {
            taskCard.remove();
        }
    };
</script>